-- MySQL Script generated by MySQL Workbench
-- Tue Mar  6 15:06:51 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema domiciliation
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema domiciliation
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `domiciliation` DEFAULT CHARACTER SET utf8 ;
USE `domiciliation` ;

-- -----------------------------------------------------
-- Table `domiciliation`.`civilite`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `domiciliation`.`civilite` (
  `id_civilite` INT(11) NOT NULL,
  `libelle_civilite` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id_civilite`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `domiciliation`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `domiciliation`.`user` (
  `id_user` INT(11) NOT NULL,
  `email` VARCHAR(150) NOT NULL,
  `mdp` VARCHAR(150) NOT NULL,
  `role_user` VARCHAR(150) NOT NULL,
  PRIMARY KEY (`id_user`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `domiciliation`.`clients`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `domiciliation`.`clients` (
  `id_client` INT(11) NOT NULL,
  `code_client` VARCHAR(45) NOT NULL,
  `nom_client` VARCHAR(145) NOT NULL,
  `siren` VARCHAR(145) NOT NULL,
  `date_contract` DATE NOT NULL,
  `domination_sociale` VARCHAR(145) NOT NULL,
  `capital` INT(11) NOT NULL,
  `id_user` INT(11) NOT NULL,
  PRIMARY KEY (`id_client`, `id_user`),
  UNIQUE INDEX `codeclient_UNIQUE` (`code_client` ASC),
  INDEX `fk_clients_user1_idx` (`id_user` ASC),
  CONSTRAINT `fk_clients_user1`
    FOREIGN KEY (`id_user`)
    REFERENCES `domiciliation`.`user` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `domiciliation`.`justificatif`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `domiciliation`.`justificatif` (
  `id_justificatif` INT(11) NOT NULL,
  `kibs` VARCHAR(45) NOT NULL,
  `piece_identite` VARCHAR(45) NOT NULL,
  `justificatif_domicile` VARCHAR(45) NOT NULL,
  `procuration_postale` VARCHAR(45) NOT NULL,
  `contract_signe` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_justificatif`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `domiciliation`.`numero_boite`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `domiciliation`.`numero_boite` (
  `id_boite` INT(11) NOT NULL,
  `numero_boite` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id_boite`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `domiciliation`.`option_contract`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `domiciliation`.`option_contract` (
  `id_option` INT(11) NOT NULL,
  `libelle_option` VARCHAR(145) NULL DEFAULT NULL,
  `id_boite` INT(11) NOT NULL,
  PRIMARY KEY (`id_option`),
  INDEX `fk_option_contract_numero_boite1_idx` (`id_boite` ASC),
  CONSTRAINT `fk_option_contract_numero_boite1`
    FOREIGN KEY (`id_boite`)
    REFERENCES `domiciliation`.`numero_boite` (`id_boite`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `domiciliation`.`contract`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `domiciliation`.`contract` (
  `id_contract` INT(11) NOT NULL,
  `debut_contract` DATE NOT NULL,
  `fin_contract` DATE NULL DEFAULT NULL,
  `motif_fin_contract` LONGTEXT NULL DEFAULT NULL,
  `annotation` LONGTEXT NULL DEFAULT NULL,
  `id_justificatif` INT(11) NOT NULL,
  `id_option` INT(11) NOT NULL,
  `id_client` INT(11) NOT NULL,
  PRIMARY KEY (`id_contract`, `id_justificatif`, `id_client`),
  INDEX `fk_contract_justificatif1_idx` (`id_justificatif` ASC),
  INDEX `fk_contract_option_contract1_idx` (`id_option` ASC),
  INDEX `fk_contract_clients1_idx` (`id_client` ASC),
  CONSTRAINT `fk_contract_justificatif1`
    FOREIGN KEY (`id_justificatif`)
    REFERENCES `domiciliation`.`justificatif` (`id_justificatif`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_contract_option_contract1`
    FOREIGN KEY (`id_option`)
    REFERENCES `domiciliation`.`option_contract` (`id_option`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_contract_clients1`
    FOREIGN KEY (`id_client`)
    REFERENCES `domiciliation`.`clients` (`id_client`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `domiciliation`.`type_courrier`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `domiciliation`.`type_courrier` (
  `id_type_courrier` INT(11) NOT NULL,
  `libelle_courrier` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_type_courrier`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `domiciliation`.`courrier`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `domiciliation`.`courrier` (
  `id_courrier` INT(11) NOT NULL,
  `numero_courrier` INT(11) NOT NULL,
  `date_entre` DATE NULL DEFAULT NULL,
  `date_sortie` DATE NULL DEFAULT NULL,
  `scan` VARCHAR(45) NOT NULL,
  `fax` VARCHAR(45) NOT NULL,
  `annotation` LONGTEXT NULL DEFAULT NULL,
  `id_client` INT(11) NOT NULL,
  `id_type_courrier` INT(11) NOT NULL,
  PRIMARY KEY (`id_courrier`, `id_client`, `id_type_courrier`),
  INDEX `fk_courrier_clients1_idx` (`id_client` ASC),
  INDEX `fk_courrier_type_courrier1_idx` (`id_type_courrier` ASC),
  CONSTRAINT `fk_courrier_clients1`
    FOREIGN KEY (`id_client`)
    REFERENCES `domiciliation`.`clients` (`id_client`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_courrier_type_courrier1`
    FOREIGN KEY (`id_type_courrier`)
    REFERENCES `domiciliation`.`type_courrier` (`id_type_courrier`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `domiciliation`.`departement`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `domiciliation`.`departement` (
  `id_departement` INT(11) NOT NULL,
  `nom` VARCHAR(145) NOT NULL,
  `numero_departement` INT(11) NOT NULL,
  PRIMARY KEY (`id_departement`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `domiciliation`.`fonction`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `domiciliation`.`fonction` (
  `id_fonction` INT(11) NOT NULL,
  `libelle` VARCHAR(145) NOT NULL,
  PRIMARY KEY (`id_fonction`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `domiciliation`.`forme_juridique`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `domiciliation`.`forme_juridique` (
  `id_forme` INT(11) NOT NULL,
  `nom` VARCHAR(145) NULL DEFAULT NULL,
  `id_client` INT(11) NOT NULL,
  PRIMARY KEY (`id_forme`, `id_client`),
  INDEX `fk_forme_juridique_clients1_idx` (`id_client` ASC),
  CONSTRAINT `fk_forme_juridique_clients1`
    FOREIGN KEY (`id_client`)
    REFERENCES `domiciliation`.`clients` (`id_client`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `domiciliation`.`incident`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `domiciliation`.`incident` (
  `id_incident` INT(11) NOT NULL,
  `date_incident` DATE NOT NULL,
  `type_incident` VARCHAR(155) NOT NULL,
  `commentaire` LONGTEXT NOT NULL,
  `id_client` INT(11) NOT NULL,
  PRIMARY KEY (`id_incident`, `id_client`),
  INDEX `fk_incident_clients1_idx` (`id_client` ASC),
  CONSTRAINT `fk_incident_clients1`
    FOREIGN KEY (`id_client`)
    REFERENCES `domiciliation`.`clients` (`id_client`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `domiciliation`.`tarif`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `domiciliation`.`tarif` (
  `id_tarif` INT(11) NOT NULL,
  `type_envoie` VARCHAR(46) NULL DEFAULT NULL,
  `tarif_envoie` DECIMAL(4,2) NULL DEFAULT NULL,
  `tarif_envelope` DECIMAL(4,2) NULL DEFAULT NULL,
  PRIMARY KEY (`id_tarif`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `domiciliation`.`lettres_recommandees`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `domiciliation`.`lettres_recommandees` (
  `id_lettre` INT(11) NOT NULL,
  `numero_envoie` VARCHAR(55) NOT NULL,
  `expediteur` VARCHAR(45) NULL DEFAULT NULL,
  `destinateur` VARCHAR(150) NULL DEFAULT NULL,
  `id_tarif` INT(11) NOT NULL,
  `id_courrier` INT(11) NOT NULL,
  PRIMARY KEY (`id_lettre`, `id_courrier`),
  INDEX `fk_lettres_recommandees_tarif1_idx` (`id_tarif` ASC),
  INDEX `fk_lettres_recommandees_courrier1_idx` (`id_courrier` ASC),
  CONSTRAINT `fk_lettres_recommandees_tarif1`
    FOREIGN KEY (`id_tarif`)
    REFERENCES `domiciliation`.`tarif` (`id_tarif`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_lettres_recommandees_courrier1`
    FOREIGN KEY (`id_courrier`)
    REFERENCES `domiciliation`.`courrier` (`id_courrier`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `domiciliation`.`pays`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `domiciliation`.`pays` (
  `id_pays` INT(11) NOT NULL,
  `nom` VARCHAR(145) NOT NULL,
  PRIMARY KEY (`id_pays`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `domiciliation`.`responsable_legale`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `domiciliation`.`responsable_legale` (
  `id_responsable` INT(11) NOT NULL,
  `nom_complet` VARCHAR(150) NOT NULL,
  `date_naissance` DATE NOT NULL,
  `lieu_naissance` VARCHAR(45) NOT NULL,
  `nationalite` VARCHAR(45) NOT NULL,
  `telephone` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `adresse` VARCHAR(45) NOT NULL,
  `id_departement` INT(11) NOT NULL,
  `id_pays` INT(11) NOT NULL,
  `id_fonction` INT(11) NOT NULL,
  `id_civilite` INT(11) NOT NULL,
  `id_client` INT(11) NOT NULL,
  PRIMARY KEY (`id_responsable`, `id_client`),
  INDEX `fk_responsable_legale_departement1_idx` (`id_departement` ASC),
  INDEX `fk_responsable_legale_pays1_idx` (`id_pays` ASC),
  INDEX `fk_responsable_legale_fonction1_idx` (`id_fonction` ASC),
  INDEX `fk_responsable_legale_civilite1_idx` (`id_civilite` ASC),
  INDEX `fk_responsable_legale_clients1_idx` (`id_client` ASC),
  CONSTRAINT `fk_responsable_legale_civilite1`
    FOREIGN KEY (`id_civilite`)
    REFERENCES `domiciliation`.`civilite` (`id_civilite`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_responsable_legale_departement1`
    FOREIGN KEY (`id_departement`)
    REFERENCES `domiciliation`.`departement` (`id_departement`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_responsable_legale_fonction1`
    FOREIGN KEY (`id_fonction`)
    REFERENCES `domiciliation`.`fonction` (`id_fonction`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_responsable_legale_pays1`
    FOREIGN KEY (`id_pays`)
    REFERENCES `domiciliation`.`pays` (`id_pays`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_responsable_legale_clients1`
    FOREIGN KEY (`id_client`)
    REFERENCES `domiciliation`.`clients` (`id_client`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `domiciliation`.`voie_reexpedition`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `domiciliation`.`voie_reexpedition` (
  `id_reexpedition` INT(11) NOT NULL,
  `libelle_reexpedition` VARCHAR(145) NOT NULL,
  `id_courrier` INT(11) NOT NULL,
  PRIMARY KEY (`id_reexpedition`, `id_courrier`),
  INDEX `fk_voie_reexpedition_courrier1_idx` (`id_courrier` ASC),
  CONSTRAINT `fk_voie_reexpedition_courrier1`
    FOREIGN KEY (`id_courrier`)
    REFERENCES `domiciliation`.`courrier` (`id_courrier`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

USE `domiciliation` ;

-- -----------------------------------------------------
-- Placeholder table for view `domiciliation`.`view_courrier`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `domiciliation`.`view_courrier` (`id_courrier` INT, `id_client` INT, `id_type_courrier` INT, `libelle_courrier` INT, `date_entre` INT, `annotation` INT, `scan` INT, `date_sortie` INT, `id_lettre` INT, `destinateur` INT, `expediteur` INT, `nom_client` INT, `code_client` INT, `libelle_reexpedition` INT, `id_reexpedition` INT, `tarif_envoie` INT);

-- -----------------------------------------------------
-- View `domiciliation`.`view_courrier`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `domiciliation`.`view_courrier`;
USE `domiciliation`;
CREATE  OR REPLACE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW `view_courrier`  AS  select `courrier`.`id_courrier` AS `id_courrier`,`courrier`.`id_client` AS `id_client`,`courrier`.`id_type_courrier` AS `id_type_courrier`,`type_courrier`.`libelle_courrier` AS `libelle_courrier`,`courrier`.`date_entre` AS `date_entre`,`courrier`.`annotation` AS `annotation`,`courrier`.`scan` AS `scan`,`courrier`.`date_sortie` AS `date_sortie`,`courrier`.`id_lettre` AS `id_lettre`,`lettres_recommandees`.`destinateur` AS `destinateur`,`lettres_recommandees`.`expediteur` AS `expediteur`,`clients`.`nom_client` AS `nom_client`,`clients`.`code_client` AS `code_client`,`voie_reexpedition`.`libelle_reexpedition` AS `libelle_reexpedition`,`voie_reexpedition`.`id_reexpedition` AS `id_reexpedition`,`tarif`.`tarif_envoie` AS `tarif_envoie` from (((((`courrier` join `clients`) join `type_courrier`) join `lettres_recommandees`) join `voie_reexpedition`) join `tarif`) where ((`courrier`.`id_client` = `clients`.`id_client`) and (`courrier`.`id_type_courrier` = `type_courrier`.`id_type_courrier`) and (`courrier`.`id_lettre` = `lettres_recommandees`.`id_lettre`) and (`courrier`.`id_reexpedition` = `voie_reexpedition`.`id_reexpedition`) and (`lettres_recommandees`.`id_tarif` = `tarif`.`id_tarif`));

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
